import React from "react";

const ExportButton = ({ article, translatedText }) => {
  const handleExport = () => {
    const content = `
NewsPulse - Professional Report
------------------------------
Title: ${article.title}
Source: ${article.source}
Date: ${new Date(article.published_at).toLocaleString()}

Summary:
${translatedText || article.summary}

Sentiment: ${article.sentiment?.mood || "N/A"} (${Math.round((article.sentiment?.score || 0) * 100)}% confidence)
Tags: ${article.tags?.join(", ") || "N/A"}

------------------------------
Generated by DigitalLens AI
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `NewsPulse_${article.title.substring(0, 20).replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <button className="mode-btn export-btn" onClick={handleExport} title="Export Report">
      📥 Export Report
    </button>
  );
};

export default ExportButton;
